name: atmos_column1
channels:
  - conda-forge
  - defaults
dependencies:
  - scipy
  - geopandas
  - numpy
  - pandas
  - cartopy
  - matplotlib
  - xarray
  - scikit-learn
  - jupyterlab
  - ipykernel
  - geographiclib
  - herbie-data
  - pynio
  - pytz
  - pysolar
  - plotly
  - netcdf4
  - cdo
  - python-cdo
  - gitpython
  - pyarrow
  - pip
  - pip:
    - simplekml
    - pylr2
    - windrose