column_type: em27
interval: 1h
start_dt_str: "2023-07-05 00:00:00"
end_dt_str: "2023-07-07 23:00:00"
timezone: UTC
inst_lat: 40.766
inst_lon: -111.847
inst_zasl: 1492
folder_paths:
  base_project_folder: /uufs/chpc.utah.edu/common/home/u0890904/LAIR_1/
  Atmos_Column_folder: /uufs/chpc.utah.edu/common/home/u0890904/LAIR_1/Atmos_Column
  column_data_folder: /uufs/chpc.utah.edu/common/home/u0890904/LAIR_1/Data/EM27_oof/ha
  output_folder: /uufs/chpc.utah.edu/common/home/u0890904/LAIR_1/Atmos_Column/output
  stilt_folder: /uufs/chpc.utah.edu/common/home/lin-group9/agm/STILT_runs/test3
  dem_folder: /uufs/chpc.utah.edu/common/home/u0890904/LAIR_1/Data/DEM
  slurm_folder: /uufs/chpc.utah.edu/common/home/u0890904/LAIR_1/Atmos_Column/slurm
  met_folder: stilt_parent
z_ail_list:
  - 0
  - 250
  - 500
  - 750
  - 1000
  - 1250
  - 1500
  - 1750
  - 2000
  - 2250
  - 2500
hrrr_subset_datestr: "2022-07-01 00:00"
met_model_type: hrrr
met_product: nat
download_met: "F"
ftp_email: agmeyer4@gmail.com
dem_fname: ASTGTM_NC.003_30m_aid0001_slcbig.nc
dem_typeid: aster
slurm_options:
  nodes: 1
  ntasks: 16
  partition: lin-np
  account: lin-np
  time: "100:00:00"
run_stilt_lib_lines:
  - library(raster)
  - library(sp)
  - library(terra)
run_stilt_configs:
  met_path: "'/uufs/chpc.utah.edu/common/home/lin-group21/hrrr/hrrr'"
  met_file_format: "'%Y%m%d_%H'"
  xmn: -112.4
  xmx: -110.8
  ymn: 40.0
  ymx: 41.4
  xres: 0.01
  yres: xres
  n_hours: -24
  numpar: 200
  slurm: "F"
